/**
 * pdf.js — PDF assembly using jsPDF
 *
 * Assembles rendered hole canvases into a printable PDF yardage book.
 * jsPDF is loaded from CDN and available as window.jspdf.jsPDF.
 *
 * PDF Layout:
 *   Page 1:     Cover page — course name, subtitle, OpenYardage credit
 *   Page 2:     Blank (for duplex printing)
 *   Pages 3–N:  One page per hole (landscape letter, 11×8.5in)
 *                 ┌─────────────────────────────────────────────┐
 *                 │ Hole N          │                           │
 *                 │ Par N           │                           │
 *                 │                 │    Full Hole Image        │
 *                 │  [Green Inset]  │    (right ~60% of page)  │
 *                 │                 │                           │
 *                 └─────────────────────────────────────────────┘
 *   Last page:  Blank (for duplex printing)
 *
 * Page dimensions (landscape letter):
 *   Width:  279mm (11in)
 *   Height: 216mm (8.5in)
 *
 * TODO (Phase 6): Implement assemblePdf() and all helper functions.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Layout constants (all in mm for jsPDF)
// ─────────────────────────────────────────────────────────────────────────────

const PAGE_W  = 279;   // mm — landscape letter width
const PAGE_H  = 216;   // mm — landscape letter height
const MARGIN  = 10;    // mm — page margin

// Left panel: ~38% of page width = ~106mm
const LEFT_PANEL_W = 106;
const LEFT_PANEL_H = PAGE_H - MARGIN * 2;

// Right panel: ~60% of page width
const RIGHT_PANEL_X = LEFT_PANEL_W + MARGIN;
const RIGHT_PANEL_W = PAGE_W - RIGHT_PANEL_X - MARGIN;
const RIGHT_PANEL_H = PAGE_H - MARGIN * 2;

// Green inset: fills bottom ~55% of left panel
const GREEN_INSET_Y = PAGE_H * 0.45;
const GREEN_INSET_H = PAGE_H - GREEN_INSET_Y - MARGIN;
const GREEN_INSET_W = LEFT_PANEL_W;

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Assemble all rendered holes into a PDF and return a data URI.
 *
 * @param {object} opts
 * @param {Array<{
 *   holeNum: number,
 *   par: number | null,
 *   holeCanvas: HTMLCanvasElement | OffscreenCanvas,
 *   greenCanvas: HTMLCanvasElement | OffscreenCanvas,
 * }>} opts.holes       — sorted by holeNum
 * @param {string} opts.courseName
 * @param {object} opts.colors   — AppState.colors
 * @returns {Promise<string>}  PDF data URI for embedding in iframe + download
 */
export async function assemblePdf({ holes, courseName, colors }) {
  // TODO (Phase 6): Implement
  //
  // const { jsPDF } = window.jspdf;
  // const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' });
  //
  // // Page 1: Cover
  // addCoverPage(pdf, courseName, colors);
  //
  // // Page 2: Blank
  // pdf.addPage();
  //
  // // Sort holes by number
  // const sorted = [...holes].sort((a, b) => a.holeNum - b.holeNum);
  //
  // for (const hole of sorted) {
  //   pdf.addPage();
  //   await addHolePage(pdf, hole, colors);
  // }
  //
  // // Last page: Blank
  // pdf.addPage();
  //
  // return pdf.output('datauristring');

  throw new Error('assemblePdf not yet implemented (Phase 6)');
}

// ─────────────────────────────────────────────────────────────────────────────
// Page builders
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Add the cover page to the PDF.
 *
 * @param {jsPDF} pdf
 * @param {string} courseName
 * @param {object} colors
 */
function addCoverPage(pdf, courseName, colors) {
  // TODO (Phase 6): Implement
  //
  // Background: rough color (converted from hex)
  // Course name: large centered text, white or contrasting color
  // Subtitle: "Yardage Book" in smaller text
  // Footer: "Generated by OpenYardage · openstreetmap.org"
  //
  // pdf.setFillColor(r, g, b);       // background
  // pdf.rect(0, 0, PAGE_W, PAGE_H, 'F');
  // pdf.setTextColor(r, g, b);
  // pdf.setFontSize(36);
  // pdf.text(courseName, PAGE_W/2, PAGE_H/2 - 20, { align: 'center' });
  // pdf.setFontSize(16);
  // pdf.text('Yardage Book', PAGE_W/2, PAGE_H/2 + 10, { align: 'center' });
  // pdf.setFontSize(9);
  // pdf.text('Generated by OpenYardage · openstreetmap.org', PAGE_W/2, PAGE_H - 12, { align: 'center' });
}

/**
 * Add a single hole page to the PDF.
 *
 * @param {jsPDF} pdf
 * @param {{ holeNum, par, holeCanvas, greenCanvas }} hole
 * @param {object} colors
 */
async function addHolePage(pdf, hole, colors) {
  // TODO (Phase 6): Implement
  //
  // Layout:
  //   Left panel (x=MARGIN, y=MARGIN, w=LEFT_PANEL_W, h=LEFT_PANEL_H):
  //     - "Hole N" title at top-left (large font)
  //     - "Par N" below title (medium font)
  //     - Green inset image in lower portion
  //
  //   Right panel (x=RIGHT_PANEL_X, y=MARGIN, w=RIGHT_PANEL_W, h=RIGHT_PANEL_H):
  //     - Full hole image, scaled to fit while preserving aspect ratio
  //
  // const holeDataUrl  = await canvasToDataUrl(hole.holeCanvas);
  // const greenDataUrl = await canvasToDataUrl(hole.greenCanvas);
  //
  // // Title
  // pdf.setFontSize(22);
  // pdf.setTextColor(0, 0, 0);
  // pdf.text(`Hole ${hole.holeNum}`, MARGIN, MARGIN + 10);
  // if (hole.par) {
  //   pdf.setFontSize(13);
  //   pdf.text(`Par ${hole.par}`, MARGIN, MARGIN + 18);
  // }
  //
  // // Full hole image (right panel)
  // const { x, y, w, h } = fitImage(hole.holeCanvas.width, hole.holeCanvas.height,
  //                                  RIGHT_PANEL_X, MARGIN, RIGHT_PANEL_W, RIGHT_PANEL_H);
  // pdf.addImage(holeDataUrl, 'PNG', x, y, w, h);
  //
  // // Green inset (lower left)
  // const gi = fitImage(hole.greenCanvas.width, hole.greenCanvas.height,
  //                     MARGIN, GREEN_INSET_Y, GREEN_INSET_W, GREEN_INSET_H);
  // pdf.addImage(greenDataUrl, 'PNG', gi.x, gi.y, gi.w, gi.h);
}

// ─────────────────────────────────────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Convert a canvas to a data URL for jsPDF.addImage().
 * Handles both OffscreenCanvas and HTMLCanvasElement.
 *
 * @param {HTMLCanvasElement | OffscreenCanvas} canvas
 * @returns {Promise<string>}
 */
export async function canvasToDataUrl(canvas) {
  if (typeof OffscreenCanvas !== 'undefined' && canvas instanceof OffscreenCanvas) {
    const blob = await canvas.convertToBlob({ type: 'image/png' });
    return blobToDataUrl(blob);
  }
  return canvas.toDataURL('image/png');
}

/**
 * Convert a Blob to a data URL via FileReader.
 *
 * @param {Blob} blob
 * @returns {Promise<string>}
 */
function blobToDataUrl(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

/**
 * Calculate image placement within a target rectangle, preserving aspect ratio
 * (letterbox / contain fit — same as CSS object-fit: contain).
 *
 * @param {number} imgW   — source image width (pixels)
 * @param {number} imgH   — source image height (pixels)
 * @param {number} boxX   — target box x (mm)
 * @param {number} boxY   — target box y (mm)
 * @param {number} boxW   — target box width (mm)
 * @param {number} boxH   — target box height (mm)
 * @returns {{ x, y, w, h }}  placement in mm
 */
export function fitImage(imgW, imgH, boxX, boxY, boxW, boxH) {
  const imgAspect = imgW / imgH;
  const boxAspect = boxW / boxH;

  let w, h;
  if (imgAspect > boxAspect) {
    // Wider than box: constrain by width
    w = boxW;
    h = boxW / imgAspect;
  } else {
    // Taller than box: constrain by height
    h = boxH;
    w = boxH * imgAspect;
  }

  // Center within box
  const x = boxX + (boxW - w) / 2;
  const y = boxY + (boxH - h) / 2;

  return { x, y, w, h };
}

/**
 * Convert a hex color string to jsPDF-compatible [r, g, b] (0-255).
 *
 * @param {string} hex  — '#RRGGBB'
 * @returns {[number, number, number]}
 */
export function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
}
